### ISSUE TITLE
Log Response Body on Error

### ISSUE THREAD

**Issue by ryanlunka** [blendededge/REST-API-component-oih#59]
When APIs respond with `4xx` errors, there is often useful information. Specifically, some APIs will return `422` and in the response body provide details about why the data sent in the request is invalid. This is necessary for understanding the problem, but we don't want to be forced to emit this to a next step.

We might as well log the response headers too, because who knows what might show up there.

I think this is where this should go, but I'm not totally sure:
https://github.com/blendededge/REST-API-component-oih/blob/02cd3f3108f58f796a114cae16c9456d6004da95/lib/utils.js#L598

**Comment by winklerj** [comment]
#60 and #61 fix this issue
